name: lint

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install black==21.4b2 \
            flake8==3.9.0                  
      - name: Run Black
        run: |
          black --check --diff fbpcs
      - name: Run Flake
        run: |
          flake8 --ignore E203,E501,W503 fbpcs
